name: CI and Deploy Lambda

on:
  push:
    branches: [ main ]

env:
  TF_VAR_region: us-east-1                 # change if needed
  TF_VAR_bucket_name: audiostichbucket     # same as used in Terraform

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('lambda/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd lambda
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/lambda
        pytest lambda/tests

    - name: Create Lambda ZIP
      run: |
        cd lambda
        zip -r ../lambda.zip .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
